In [3]:
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import tensorflow as tf
import os
from PIL import Image

In [4]:
import os

In [5]:
%pwd

'd:\\Project\\Leaf_Disease_Classification\\research'

In [6]:
os.chdir('../')

In [7]:
%pwd

'd:\\Project\\Leaf_Disease_Classification'

In [8]:
class_names = ['Pepper__bell___Bacterial_spot',
                        'Pepper__bell___healthy',
                        'Potato___Early_blight',
                        'Potato___Late_blight',
                        'Potato___healthy',
                        'Tomato_Bacterial_spot',
                        'Tomato_Early_blight',
                        'Tomato_Late_blight',
                        'Tomato_Leaf_Mold',
                        'Tomato_Septoria_leaf_spot',
                        'Tomato_Spider_mites_Two_spotted_spider_mite',
                        'Tomato__Target_Spot',
                        'Tomato__Tomato_YellowLeaf__Curl_Virus',
                        'Tomato__Tomato_mosaic_virus',
                        'Tomato_healthy']

In [9]:
from PIL import Image
image = Image.open('D:/Project/Leaf_Disease_Classification/artifacts/data_ingestion/plant-village/PlantVillage/Pepper__bell___Bacterial_spot/0a0dbf1f-1131-496f-b337-169ec6693e6f___NREC_B.Spot 9241.JPG')
print(image.format)
print(image.size)
print(image.mode)
image
img = np.asarray(image)
print(type(img))
print(img.shape)
print(img)

JPEG
(256, 256)
RGB
<class 'numpy.ndarray'>
(256, 256, 3)
[[[196 192 193]
  [192 188 189]
  [183 179 180]
  ...
  [171 165 167]
  [167 161 163]
  [166 160 162]]

 [[206 202 203]
  [189 185 186]
  [172 168 169]
  ...
  [179 173 175]
  [181 175 177]
  [184 178 180]]

 [[177 173 174]
  [167 163 164]
  [167 163 164]
  ...
  [173 167 169]
  [177 171 173]
  [183 177 179]]

 ...

 [[127 115 117]
  [120 108 110]
  [135 123 125]
  ...
  [124 113 117]
  [119 108 112]
  [120 109 113]]

 [[122 110 112]
  [127 115 117]
  [137 125 127]
  ...
  [166 155 159]
  [128 117 121]
  [185 174 178]]

 [[133 121 123]
  [127 115 117]
  [127 115 117]
  ...
  [104  93  97]
  [135 124 128]
  [134 123 127]]]


In [10]:
model = load_model(os.path.join("artifacts","training", "model.h5"))
image = Image.open('D:/Project/Leaf_Disease_Classification/artifacts/data_ingestion/plant-village/PlantVillage/Pepper__bell___Bacterial_spot/0a0dbf1f-1131-496f-b337-169ec6693e6f___NREC_B.Spot 9241.JPG')
image = image.resize((224,224))
img = np.asarray(image)
# img_array = tf.keras.preprocessing.image.img_to_array(img.numpy())
# test_image = image.load_img(imagename, target_size = (224,224))
img_array = tf.expand_dims(img, 0)
predictions = model.predict(img_array)
predicted_class = class_names[np.argmax(predictions[0])]
predicted_class

1/1 [==============================] - 1s 875ms/step


'Pepper__bell___Bacterial_spot'

In [11]:
class PredictionPipeline:
    def __init__(self,filename):
        self.filename =filename


    
    def predict(self):
        # load model
        model = load_model(os.path.join("artifacts","training", "model.h5"))
        imagename = self.filename

        image = Image.open(imagename)
        image = image.resize((224,224))
        img = np.asarray(image)
        img_array = tf.expand_dims(img, 0)

        class_names = ['Pepper__bell___Bacterial_spot',
                        'Pepper__bell___healthy',
                        'Potato___Early_blight',
                        'Potato___Late_blight',
                        'Potato___healthy',
                        'Tomato_Bacterial_spot',
                        'Tomato_Early_blight',
                        'Tomato_Late_blight',
                        'Tomato_Leaf_Mold',
                        'Tomato_Septoria_leaf_spot',
                        'Tomato_Spider_mites_Two_spotted_spider_mite',
                        'Tomato__Target_Spot',
                        'Tomato__Tomato_YellowLeaf__Curl_Virus',
                        'Tomato__Tomato_mosaic_virus',
                        'Tomato_healthy']

        predictions = model.predict(img_array)
        predicted_class = class_names[np.argmax(predictions[0])]
        print(predicted_class)
        return [{"image": predicted_class}]

In [12]:
pred = PredictionPipeline('D:/Project/Leaf_Disease_Classification/artifacts/data_ingestion/plant-village/PlantVillage/Pepper__bell___Bacterial_spot/0a0dbf1f-1131-496f-b337-169ec6693e6f___NREC_B.Spot 9241.JPG')
result = pred.predict()

1/1 [==============================] - 1s 548ms/step
Pepper__bell___Bacterial_spot


In [13]:
result

[{'image': 'Pepper__bell___Bacterial_spot'}]